# -*- coding: utf-8 -*-
"""EE541HW5ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RL2YRfLvKiCqYtImoQ8HJjKLGLcUPE68
"""

import numpy as np
import h5py
import matplotlib.pyplot as plt

# read in data
# Load the data
with h5py.File('mnist_traindata.hdf5', 'r') as f:
    X_train = f['xdata'][:]
    y_train = f['ydata'][:]

with h5py.File('mnist_testdata.hdf5', 'r') as f:
    X_test = f['xdata'][:]
    y_test = f['ydata'][:]

print("X_train shape:", X_train.shape)  # (60000, 784)
print("y_train shape:", y_train.shape)  # (60000, 10)
print("X_test shape:", X_test.shape)    # (10000, 784)
print("y_test shape:", y_test.shape)    # (10000, 10)

# softmax function
def softmax(z):
    z = z - np.max(z, axis=1, keepdims=True)
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

# sigmoid functiom
def sigmoid(z):
    return np.where(z >= 0,
                  1 / (1 + np.exp(-z)),
                  np.exp(z) / (1 + np.exp(z)))

# sanity check
# initialize weights and bias
W = np.zeros((784, 10))  # 784 pixels, 10 classes
b = np.zeros(10)         # one bias per class

# compute raw scores and probabilities
z = X_train @ W + b      # shape: (60000, 10)
probs = softmax(z)        # shape: (60000, 10)

print("Probs shape:", probs.shape)
print("Sample probabilities for first image:", probs[0])
print("Sum of probabilities:", probs[0].sum())

def cross_entropy_loss(y_true, y_pred):

    y_pred = np.clip(y_pred, 1e-12, 1 - 1e-12)
    # multiply true labels by log of predicted probabilities

    return -np.mean(np.sum(y_true * np.log(y_pred), axis=1))

probs = softmax(X_train @ W + b)
loss = cross_entropy_loss(y_train, probs)
print("Initial loss:", loss)

# compute gradient for n namples
def compute_gradient(X, y_true, y_pred, W, lambda_reg=0, reg_type=None):
    n_samples = X.shape[0]

    # difference between predicted probabilities and true one-hot labels
    diff = y_pred - y_true  # shape: (n_samples, 10)

    # gradient for weights and bias
    grad_W = X.T @ diff / n_samples  # shape: (784, 10)
    grad_b = np.mean(diff, axis=0)   # shape: (10,)

    # regularization
    if reg_type == 'l2' and lambda_reg > 0:
        grad_W += lambda_reg * W
    elif reg_type == 'l1' and lambda_reg > 0:
        grad_W += lambda_reg * np.sign(W)

    return grad_W, grad_b

probs = softmax(X_train @ W + b)
grad_W, grad_b = compute_gradient(X_train, y_train, probs, W)

print("grad_W shape:", grad_W.shape)
print("grad_b shape:", grad_b.shape)
print("Max abs gradient:", np.abs(grad_W).max())

def gradient_descent(X_train, y_train, X_test, y_test,
                     learning_rate=0.1, max_iter=1000,
                     lambda_reg=0, reg_type=None, tol=1e-6):

    n_features = X_train.shape[1]
    n_classes = y_train.shape[1] #

    # initialize weights and bias
    W = np.zeros((n_features, n_classes))  # (784, 10)
    b = np.zeros(n_classes)                # (10,)

    train_losses, test_losses = [], []
    train_accs, test_accs = [], []

    for i in range(max_iter):
        # forward pass
        y_pred_train = softmax(X_train @ W + b)
        y_pred_test  = softmax(X_test @ W + b)

        # track loss and accuracy
        train_loss = cross_entropy_loss(y_train, y_pred_train)
        test_loss  = cross_entropy_loss(y_test, y_pred_test)
        train_losses.append(train_loss)
        test_losses.append(test_loss)

        # accuracy: pick highest probability class and compare to true label
        train_accs.append(np.mean(np.argmax(y_pred_train, axis=1) == np.argmax(y_train, axis=1)))
        test_accs.append(np.mean(np.argmax(y_pred_test, axis=1)  == np.argmax(y_test, axis=1)))

        # convergence check
        if i > 0 and abs(train_losses[-2] - train_losses[-1]) < tol:
            print(f"Converged at iteration {i}")
            break

        # compute gradients and update
        grad_W, grad_b = compute_gradient(X_train, y_train, y_pred_train, W, lambda_reg, reg_type)
        W -= learning_rate * grad_W
        b -= learning_rate * grad_b

    return W, b, train_losses, test_losses, train_accs, test_accs

for lr in [0.1, 0.01, 0.001]:
    W_t, b_t, trl, tel, tra, tea = gradient_descent(
        X_train, y_train, X_test, y_test,
        learning_rate=lr, max_iter=100)
    print(f"lr={lr}: final loss={trl[-1]:.4f}, accuracy={tra[-1]:.4f}")

W, b, train_losses, test_losses, train_accs, test_accs = gradient_descent(
    X_train, y_train, X_test, y_test,
    learning_rate=0.1, max_iter=10000)

print(f"Final train loss: {train_losses[-1]:.4f}")
print(f"Final test loss:  {test_losses[-1]:.4f}")
print(f"Final train accuracy: {train_accs[-1]:.4f}")
print(f"Final test accuracy:  {test_accs[-1]:.4f}")

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))

# Loss curve
ax1.plot(train_losses, label='Train Loss', color='blue', linewidth=2)
ax1.plot(test_losses, label='Test Loss', color='orange', linewidth=2, linestyle='--')
ax1.set_xlabel('Iteration')
ax1.set_ylabel('Log Loss')
ax1.set_title('Softmax: Learning Curve - Loss vs Iteration')
ax1.legend()
ax1.grid(True)

# Accuracy curve
ax2.plot(train_accs, label='Train Accuracy', color='blue', linewidth=2)
ax2.plot(test_accs, label='Test Accuracy', color='orange', linewidth=2, linestyle='--')
ax2.set_xlabel('Iteration')
ax2.set_ylabel('Accuracy')
ax2.set_title('Softmax: Learning Curve - Accuracy vs Iteration')
ax2.legend()
ax2.grid(True)

plt.tight_layout()
plt.show()

print(f"Converged at iteration: {len(train_losses)}")

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))

# Loss curve
ax1.plot(train_losses, label='Train Loss', color='blue', linewidth=2)
ax1.plot(test_losses, label='Test Loss', color='orange', linewidth=2, linestyle='--')
ax1.set_xlabel('Iteration')
ax1.set_ylabel('Log Loss')
ax1.set_title('Softmax: Learning Curve - Loss vs Iteration')
ax1.legend()
ax1.grid(True)

# zoomed inset for loss
ax1_inset = ax1.inset_axes([0.4, 0.4, 0.55, 0.5])
ax1_inset.plot(train_losses, color='blue', linewidth=2)
ax1_inset.plot(test_losses, color='orange', linewidth=2, linestyle='--')
ax1_inset.set_xlim(7000, 10000)
ax1_inset.set_ylim(0.260, 0.275)
ax1_inset.set_title('Zoomed: iterations 7000-10000', fontsize=8)
ax1_inset.grid(True)

# Accuracy curve
ax2.plot(train_accs, label='Train Accuracy', color='blue', linewidth=2)
ax2.plot(test_accs, label='Test Accuracy', color='orange', linewidth=2, linestyle='--')
ax2.set_xlabel('Iteration')
ax2.set_ylabel('Accuracy')
ax2.set_title('Softmax: Learning Curve - Accuracy vs Iteration')
ax2.legend()
ax2.grid(True)

# zoomed inset for accuracy
ax2_inset = ax2.inset_axes([0.4, 0.1, 0.55, 0.5])
ax2_inset.plot(train_accs, color='blue', linewidth=2)
ax2_inset.plot(test_accs, color='orange', linewidth=2, linestyle='--')
ax2_inset.set_xlim(7000, 10000)
ax2_inset.set_ylim(0.920, 0.930)
ax2_inset.set_title('Zoomed: iterations 7000-10000', fontsize=8)
ax2_inset.grid(True)

plt.tight_layout()
plt.show()

with h5py.File('softmax_weights.hdf5', 'w') as hf:
    hf.create_dataset('W', data=np.asarray(W))
    hf.create_dataset('b', data=np.asarray(b))

print("W shape:", W.shape)
print("b shape:", b.shape)
print("Saved successfully!")

def sgd(X_train, y_train, X_test, y_test,
        learning_rate=0.1, max_epochs=10,
        batch_size=1, record_every=5000):

    n_samples, n_features = X_train.shape
    n_classes = y_train.shape[1]

    W = np.zeros((n_features, n_classes))
    b = np.zeros(n_classes)

    train_losses, test_losses = [], []
    train_accs, test_accs = [], []
    samples_seen = 0
    next_record = 0  # record at sample 0, 5000, 10000, etc.

    def record_metrics():
        y_pred_train = softmax(X_train @ W + b)
        y_pred_test  = softmax(X_test @ W + b)
        train_losses.append(cross_entropy_loss(y_train, y_pred_train))
        test_losses.append(cross_entropy_loss(y_test, y_pred_test))
        train_accs.append(np.mean(np.argmax(y_pred_train, axis=1) == np.argmax(y_train, axis=1)))
        test_accs.append(np.mean(np.argmax(y_pred_test,  axis=1) == np.argmax(y_test,  axis=1)))

    # record initial performance before any training
    record_metrics()
    next_record = record_every

    for epoch in range(max_epochs):
        # shuffle data at the start of each epoch
        idx = np.random.permutation(n_samples)
        X_shuffled = X_train[idx]
        y_shuffled = y_train[idx]

        for start in range(0, n_samples, batch_size):
            # grab mini batch
            X_batch = X_shuffled[start:start + batch_size]
            y_batch = y_shuffled[start:start + batch_size]

            # forward pass and update
            y_pred = softmax(X_batch @ W + b)
            grad_W, grad_b = compute_gradient(X_batch, y_batch, y_pred, W)
            W -= learning_rate * grad_W
            b -= learning_rate * grad_b

            samples_seen += batch_size

            # record every 5000 samples
            if samples_seen >= next_record:
                record_metrics()
                next_record += record_every

    return W, b, train_losses, test_losses, train_accs, test_accs

#SGD batch 1
np.random.seed(42)
W_sgd1, b_sgd1, trl1, tel1, tra1, tea1 = sgd(
    X_train, y_train, X_test, y_test,
    learning_rate=0.1, max_epochs=5, batch_size=1)

print(f"Final train loss: {trl1[-1]:.4f}")
print(f"Final test loss:  {tel1[-1]:.4f}")
print(f"Final train acc:  {tra1[-1]:.4f}")
print(f"Final test acc:   {tea1[-1]:.4f}")

# try more epochs and a smaller learning rate
for lr, epochs in [(0.1, 10), (0.01, 10), (0.01, 20)]:
    np.random.seed(42)
    W_t, b_t, trl, tel, tra, tea = sgd(
        X_train, y_train, X_test, y_test,
        learning_rate=lr, max_epochs=epochs, batch_size=1)
    print(f"lr={lr}, epochs={epochs}: train_loss={trl[-1]:.4f}, train_acc={tra[-1]:.4f}, test_acc={tea[-1]:.4f}")

np.random.seed(42)
W_sgd1, b_sgd1, trl1, tel1, tra1, tea1 = sgd(
    X_train, y_train, X_test, y_test,
    learning_rate=0.01, max_epochs=10, batch_size=1)

# x axis is in units of 5000 samples
samples = [i * 5000 for i in range(len(trl1))]

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))

ax1.plot(samples, trl1, label='Train Loss', color='blue', linewidth=2)
ax1.plot(samples, tel1, label='Test Loss', color='orange', linewidth=2, linestyle='--')
ax1.set_xlabel('Samples Seen')
ax1.set_ylabel('Log Loss')
ax1.set_title('SGD (batch=1): Loss vs Samples Seen')
ax1.legend()
ax1.grid(True)

ax2.plot(samples, tra1, label='Train Accuracy', color='blue', linewidth=2)
ax2.plot(samples, tea1, label='Test Accuracy', color='orange', linewidth=2, linestyle='--')
ax2.set_xlabel('Samples Seen')
ax2.set_ylabel('Accuracy')
ax2.set_title('SGD (batch=1): Accuracy vs Samples Seen')
ax2.legend()
ax2.grid(True)

plt.tight_layout()
plt.show()

#SGD Batch 100
np.random.seed(42)
W_sgd1, b_sgd1, trl1, tel1, tra1, tea1 = sgd(
    X_train, y_train, X_test, y_test,
    learning_rate=0.1, max_epochs=5, batch_size=100)

print(f"Final train loss: {trl1[-1]:.4f}")
print(f"Final test loss:  {tel1[-1]:.4f}")
print(f"Final train acc:  {tra1[-1]:.4f}")
print(f"Final test acc:   {tea1[-1]:.4f}")

# x axis is in units of 5000 samples
samples = [i * 5000 for i in range(len(trl1))]

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))

ax1.plot(samples, trl1, label='Train Loss', color='blue', linewidth=2)
ax1.plot(samples, tel1, label='Test Loss', color='orange', linewidth=2, linestyle='--')
ax1.set_xlabel('Samples Seen')
ax1.set_ylabel('Log Loss')
ax1.set_title('SGD (batch=100): Loss vs Samples Seen')
ax1.legend()
ax1.grid(True)

ax2.plot(samples, tra1, label='Train Accuracy', color='blue', linewidth=2)
ax2.plot(samples, tea1, label='Test Accuracy', color='orange', linewidth=2, linestyle='--')
ax2.set_xlabel('Samples Seen')
ax2.set_ylabel('Accuracy')
ax2.set_title('SGD (batch=100): Accuracy vs Samples Seen')
ax2.legend()
ax2.grid(True)

plt.tight_layout()
plt.show()